org: sandeepzgk
app: vt-haptics-platform
service: core
frameworkVersion: '3'

custom:
  tableName: 'data-table-${sls:stage}'
  bucketName: 'haptic-bucket-${sls:stage}'
  dynamodb:
    start:
      migrate: false
    stages:
      - dev

provider:
  name: aws
  runtime: nodejs14.x
  timeout: 1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ DataTable, Arn ]
        - Effect: 'Allow'
          Action:
            - "s3:GetObject"
            - "s3:PutObject"
          Resource:
            Fn::Join:
              - ''
              - - 'arn:aws:s3:::'
                - !Ref StorageBucket
                - '/*'
           

  environment:
    DATA_TABLE: ${self:custom.tableName}
    STORAGE_BUCKET: ${self:custom.bucketName}

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'

resources:
  Resources:
    DataTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: expid
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: expid
            KeyType: HASH
          - AttributeName: email
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}
    StorageBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
    
plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-s3-local
